version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Root user for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: admin  # Password for the root user
    networks:
      - mynetwork

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  invoice-service:
    build:
      context: ./invoice-service
    restart: always 
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - mynetwork

  notifier-service:
    build:
      context: ./notifier-service
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - mynetwork

volumes:
  mongo-data:  # Named volume to persist data

networks:
  mynetwork:
    driver: bridge
